# Generated by Django 4.1.7 on 2023-08-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarista',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
