# Generated by Django 4.1.7 on 2023-08-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_initial'),
        ('nomencladores', '0002_alter_comentarista_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarista',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.RemoveField(
            model_name='lineafinanciamiento',
            name='moneda',
        ),
        migrations.AddField(
            model_name='lineafinanciamiento',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomencladores.moneda'),
        ),
    ]
