# Generated by Django 4.1.7 on 2023-08-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0003_alter_comentarista_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineafinanciamiento',
            name='activa',
            field=models.BooleanField(default=False),
        ),
    ]
