# Generated by Django 4.1.7 on 2023-08-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0004_lineafinanciamiento_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoprestamista',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='puertoembarque',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
    ]
