# Generated by Django 4.1.7 on 2023-08-14 15:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0006_alter_grupoproductos_comentarista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoproductos',
            name='productos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
