# Generated by Django 4.1.7 on 2023-07-19 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigParametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_crear_sao', models.IntegerField()),
                ('limite_aprobacion_division', models.IntegerField()),
                ('num_aprob_sao', models.IntegerField()),
                ('nomenclador_general', models.CharField(max_length=50)),
                ('proveedores', models.CharField(max_length=50)),
                ('inversiones', models.CharField(max_length=50)),
                ('sao', models.CharField(max_length=50)),
                ('entidades', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=128)),
                ('usuarios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
