# Generated by Django 4.1.7 on 2023-07-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configparametros',
            name='entidades',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='configparametros',
            name='inversiones',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='configparametros',
            name='nomenclador_general',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='configparametros',
            name='proveedores',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='configparametros',
            name='sao',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
