# Generated by Django 4.1.7 on 2023-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_configparametros_entidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configparametros',
            name='limite_aprobacion_division',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configparametros',
            name='limite_crear_sao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configparametros',
            name='num_aprob_sao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
