# Generated by Django 4.1.7 on 2023-07-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_configparametros_limite_aprobacion_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configparametros',
            name='num_aprob_sao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
