# Generated by Django 4.1.7 on 2023-08-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_initial'),
        ('administracion', '0004_alter_configparametros_num_aprob_sao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=30)),
                ('comparacion', models.CharField(max_length=30)),
                ('valor', models.CharField(max_length=30)),
                ('siguiente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAprobador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificar_a', models.EmailField(max_length=254)),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.condicion')),
                ('sustituto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_sustituto', to='usuario.usuario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_aprobador', to='usuario.usuario')),
            ],
        ),
    ]
