# Generated by Django 4.1.7 on 2023-08-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_initial'),
        ('administracion', '0005_condicion_perfilaprobador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='entidad',
            name='productos',
            field=models.ManyToManyField(related_name='usuarios_entidad', to='usuario.usuario'),
        ),
    ]
