# Generated by Django 4.1.7 on 2023-08-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_remove_entidad_usuarios_entidad_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidad',
            old_name='productos',
            new_name='usuarios',
        ),
    ]
